version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'  # Map container port 5432 to host port 5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=shortlinks

  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'  # Map container port 6379 to host port 6379
    environment:
      - REDIS_PASSWORD=docker